export interface GuideArticle {
  id: string;
  title: string;
  keywords?: string[];
  body: string;
}

export interface GuideSection {
  id: string;
  title: string;
  articles: GuideArticle[];
}

export const guideSections: GuideSection[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    articles: [
      {
        id: "gs-what",
        title: "What is ScholarAI?",
        keywords: ["overview", "intro", "about", "rag"],
        body: `ScholarAI is a **local-first study assistant**. It reads your own materials — PDFs, Markdown, notes — and turns them into an answerable, studyable knowledge base that lives entirely on your machine.

Everything runs locally: your documents are chunked, embedded, and indexed in a local vector store, and answers are generated by local models. Nothing is sent to the cloud.

**Where to start:** add a few documents on the [Documents](#gs-import) page, then try [Ask AI](#feat-ask), [Teach Me](#feat-teach), or generate study material.`,
      },
      {
        id: "gs-import",
        title: "Add your first documents",
        keywords: ["upload", "import", "pdf", "documents", "ingest"],
        body: `Open **Documents** and drag & drop your files, or click *Browse files*. Supported formats: PDF, Markdown, and plain text.

Each file is processed automatically — text extraction → chunking → embedding → indexing. Once indexing finishes, the document is searchable everywhere in the app.

> Tip: group related material into a **course** so you can scope answers and study sets to one subject.`,
      },
      {
        id: "gs-ollama",
        title: "Set up Ollama (model backend)",
        keywords: ["ollama", "models", "setup", "install", "local"],
        body: `ScholarAI runs all AI models locally through **Ollama**. You need it installed and running before the app can answer questions or generate study material.

**Install:** Download from [ollama.ai](https://ollama.ai) or your package manager (\`brew install ollama\`, \`winget install Ollama.Ollama\`). Start it with \`ollama serve\`.

**Pull required models (minimum set):**
\`\`\`bash
ollama pull llama3.2:latest
ollama pull qwen3:8b
ollama pull nomic-embed-text
\`\`\`

Larger models like \`gemma4:12b\` or \`qwen2.5vl:7b\` (for vision) improve quality but need ~16 GB+ RAM.

The model list in \`config/default.toml\` controls which model handles which task. Copy to \`config/local.toml\` and edit to override.

If Ollama runs on a non-default host or port, update \`[ollama] → base_url\` in \`local.toml\`.`,
      },
      {
        id: "gs-first-answer",
        title: "Get your first answer",
        keywords: ["ask", "question", "answer", "citations"],
        body: `Go to **Ask AI**, optionally narrow the scope to a course or single document, type a question, and send. Answers are grounded in your materials and cite the exact sources they came from — click a citation to see the passage.

If you'd rather *learn* a topic than just ask about it, try [Teach Me](#feat-teach).`,
      },
    ],
  },
  {
    id: "core-concepts",
    title: "Core Concepts",
    articles: [
      {
        id: "cc-rag",
        title: "Source-grounded answers (RAG)",
        keywords: ["rag", "retrieval", "grounding", "citations", "hallucination"],
        body: `ScholarAI uses **retrieval-augmented generation**: before answering, it retrieves the most relevant chunks from your indexed documents and asks the model to answer *only* from them. That's why answers carry citations — and why adding more (and better) source material directly improves answer quality.

If an answer can't be supported by your materials, the assistant should say so rather than guess.

You can inspect exactly which chunks were retrieved and how they scored by checking the [RAG Trace](#feat-trace).`,
      },
      {
        id: "cc-courses",
        title: "Courses & documents",
        keywords: ["course", "organize", "scope", "subject"],
        body: `A **course** is a workspace that groups related documents. Scoping a question, quiz, or revision sheet to a course keeps retrieval focused and results relevant.

You can leave everything in one place, but organizing by course pays off once you have material for several subjects. Courses are managed from the **Courses** page.`,
      },
      {
        id: "cc-artifacts",
        title: "Study artifacts",
        keywords: ["flashcards", "quiz", "mindmap", "diagram", "generate", "artifact"],
        body: `Generated study material — flashcards, quizzes, concept graphs, mind maps, diagrams, difference tables, revision sheets, whiteboards — is created on demand from your documents and saved so you can return to it. Most artifacts live in the sidebar under *Study Tools* or *Workspace*.

Each artifact type has a dedicated page with its own viewer and management. Generate from the relevant page, review, and regenerate any time as your materials grow.`,
      },
    ],
  },
  {
    id: "features",
    title: "Features",
    articles: [
      {
        id: "feat-ask",
        title: "Ask AI",
        keywords: ["ask", "chat", "answer", "sources", "socratic"],
        body: `Conversational, source-grounded Q&A over your materials. Narrow the scope to a course or document, ask, and inspect the cited passages in the sources panel.

**Socratic mode** — toggle it on to be guided toward answers instead of handed them. The AI asks questions, hints, and counter-questions to help you reason through the material yourself. Useful when you want to test understanding rather than get a quick answer.

The **Selection Toolbar** (floating buttons that appear when you select text in the answer) lets you drill deeper, ask follow-ups, or add content to a notebook without retyping anything.`,
      },
      {
        id: "feat-teach",
        title: "Teach Me",
        keywords: ["teach", "learn", "lesson", "explain"],
        body: `Pick a concept and ScholarAI builds an interactive learning package — explanations plus supporting artifacts — to teach it step by step. Best when you want to *understand* a topic from scratch rather than get a single answer.

Teach Me generates a structured lesson with explanations, examples, and follow-up artifacts tailored to your source material.`,
      },
      {
        id: "feat-reading",
        title: "Reading",
        keywords: ["reading", "deep", "lens", "highlight", "annotation", "sticky"],
        body: `Read a document in a focused reader with AI on the side. Two document types are supported:

- **Text documents** — rendered with a side panel for AI context, notes, and drawing tools.
- **PDFs** — rendered page by page with zoom, scrolling, and highlights.

**Academic lens** — adjust the difficulty level (Beginner / Intermediate / Expert) to simplify dense text or get more rigorous explanations.

**Annotations** — add categorized sticky notes (Insight, Question, Formula, Warning) and draw regions on PDF pages. Notes sync across sessions and can be exported to notebooks.

**Highlighting & bookmarks** — mark important passages and bookmark pages for quick reference.

**Selection Toolbar** — select any text to get AI actions (explain, summarize, define) without leaving the page.`,
      },
      {
        id: "feat-study",
        title: "Flashcards, Quizzes & more",
        keywords: ["flashcards", "quiz", "mindmap", "diagram", "differences", "revision"],
        body: `Generate spaced-repetition **flashcards**, self-test **quizzes**, interactive **mind maps**, visual **diagrams**, comparison **difference tables**, and exam-ready **revision** sheets — each grounded in your own material.

| Tool | Page | What it does |
| --- | --- | --- |
| Flashcards | \`/flashcards\` | Spaced-repetition review cards with rating |
| Quiz | \`/quiz\` | Self-test with multiple question types |
| Mind Maps | \`/mindmaps\` | Interactive tree of concept relationships |
| Diagrams | \`/diagrams\` | Auto-generated visual diagrams from your material |
| Differences | \`/differences\` | Side-by-side concept comparisons |
| Revision | \`/revision\` | Concise exam-ready summary sheets |

Generated artifacts carry a **quality score** (shown as a badge) so you can gauge confidence before studying.`,
      },
      {
        id: "feat-exam",
        title: "Exam & PYQ Analysis",
        keywords: ["exam", "mock", "simulate", "pyq", "previous year"],
        body: `**Exam Simulation** — take a timed mock exam generated from your materials. After submitting, review your performance question by question.

**PYQ Analysis** — upload previous-year question papers. The AI analyzes them to surface question patterns, topic frequency, and high-yield areas so you know what to focus on.`,
      },
      {
        id: "feat-knowledge",
        title: "Knowledge Base (Concept Graph)",
        keywords: ["knowledge", "graph", "concept", "map", "relationships", "mastery"],
        body: `The **Knowledge Base** visualizes concepts extracted from your documents as an interactive graph. Each node is a concept, edges show relationships between them.

**Explore the graph** — pan, zoom, click nodes to inspect their source passages in the side panel. Filter by degree of separation, source document, or concept type.

**Mastery tracking** — mark concepts as Unknown / Learning / Weak / Needs Revision / Mastered. Filter the graph by mastery level to focus on what needs attention.

**Dependency view** — visualize which concepts build on which. See what prerequisites you need before tackling advanced topics.

**Collections** — save groups of related concepts for focused study sessions.`,
      },
      {
        id: "feat-notebooks",
        title: "Notebooks",
        keywords: ["notebook", "notes", "write", "editor", "draft"],
        body: `**Notebooks** is a block-based rich text editor for creating and organizing your own study notes alongside your imported documents.

**AI writing assistant** — while writing, ask the AI to continue, rewrite, summarize, or expand sections — all grounded in your source material.

**Notebook citations** — reference specific passages from your documents; citations resolve automatically.

**Auto-save** — drafts are saved automatically as you type. Never lose work.

Find saved notebooks in the sidebar under *Workspace*.`,
      },
      {
        id: "feat-learning-path",
        title: "Learning Path",
        keywords: ["roadmap", "path", "plan", "progress", "staged"],
        body: `The **Learning Path** generates a dependency-ordered study roadmap for a topic. Concepts are arranged so you learn prerequisites before advanced material.

**Staged progression** — each concept shows its status: Not Started → Learning → Reviewing → Mastered. Work through them in order.

**Analytics** — see estimated time per concept, overall progress, and which concepts are blocking your advancement. The path adapts as you mark concepts complete.

Available from the sidebar under *Workspace*.`,
      },
      {
        id: "feat-whiteboards",
        title: "Whiteboards",
        keywords: ["whiteboard", "canvas", "draw", "diagram", "excalidraw", "mermaid"],
        body: `**Whiteboards** provides a free-form visual canvas (powered by Excalidraw) for drawing diagrams, flowcharts, mind maps, and sketches.

**AI generation** — describe a diagram in text and the AI creates editable elements on your canvas. Convert Mermaid diagrams to editable drawings.

**Sources** — whiteboards can be created manually, AI-generated, imported from Mermaid, or from text selections in Reading mode.

**Revision history** — every change is tracked. Browse, diff, and restore previous versions.

**Scratchpad** — a quick-draw canvas available from any page via the bottom drawer. Use it for temporary sketches without leaving your current view.`,
      },
      {
        id: "feat-search",
        title: "Global Search",
        keywords: ["search", "find", "semantic", "hybrid", "discover"],
        body: `Press \`⌘K\` (or click the search bar) to open **Global Search**. It runs hybrid search (semantic + BM25 keyword) across every chunk in your indexed documents.

Filter by course to narrow results. Click any result to jump to the source document and passage. Use it to quickly find material you know exists but can't remember where.

The command palette (also \`⌘K\`) doubles as a launcher — type a page name to navigate instantly.`,
      },
      {
        id: "feat-trace",
        title: "RAG Trace",
        keywords: ["trace", "debug", "retrieval", "analytics", "pipeline"],
        body: `**RAG Trace** shows you exactly what happened when you asked a question: which chunks were retrieved, their similarity scores, and which passages the model used to answer.

Open it from the sidebar or after an Ask AI response. Use it to understand why an answer was (or wasn't) relevant — and to check that your documents are being retrieved correctly.

The trace also includes aggregate analytics about your retrieval pipeline.`,
      },
      {
        id: "feat-consistency",
        title: "Consistency Analysis",
        keywords: ["consistency", "verify", "validate", "check", "accuracy"],
        body: `**Consistency Analysis** checks generated study artifacts against your source material. It identifies:

- Claims in flashcards, quizzes, or notes that aren't supported by the source
- Misalignments between your notes and the original documents
- Internal contradictions across your study material

Run it on individual artifacts or your entire course. Use it before exams to catch mistakes early.`,
      },
      {
        id: "feat-prompts",
        title: "Prompt Library",
        keywords: ["prompt", "template", "customize", "save"],
        body: `The **Prompt Library** stores reusable prompt templates organized by task. Each template controls how the AI behaves for a specific feature.

Edit any prompt to customize the AI's instructions, tone, or output format. Changes take effect immediately. Default prompts are populated on first run and can be restored.

Access the library from the sidebar under *System*.`,
      },
    ],
  },
  {
    id: "workflows",
    title: "Workflows",
    articles: [
      {
        id: "wf-import",
        title: "Importing & organizing material",
        keywords: ["import", "organize", "course", "setup"],
        body: `1. Create or pick a **course** for the subject.
2. Add documents on the **Documents** page (drag & drop).
3. Wait for indexing to finish.
4. Confirm it worked by asking a quick question in [Ask AI](#feat-ask).

Good inputs make every other tool better — start here.`,
      },
      {
        id: "wf-learn",
        title: "Learning a new topic",
        keywords: ["learn", "study", "new topic", "teach"],
        body: `1. Use [Teach Me](#feat-teach) to get a structured explanation.
2. Read the source in [Reading](#feat-reading), lowering the lens if it's dense.
3. Ask follow-ups in [Ask AI](#feat-ask) for anything unclear.
4. Lock it in with [flashcards](#feat-study).

For complex topics, start with the [Learning Path](#feat-learning-path) to see the dependency order.`,
      },
      {
        id: "wf-exam",
        title: "Preparing for an exam",
        keywords: ["exam", "prep", "revision", "mock", "practice"],
        body: `1. Generate a **revision** sheet for each topic.
2. Run a **quiz** to find weak spots.
3. Take a full **Exam** simulation under time pressure.
4. Review misses and revisit those topics.

Use [Consistency Analysis](#feat-consistency) to verify your study artifacts are accurate. Check [PYQ Analysis](#feat-exam) to spot exam patterns. Repeat until scores stabilize.`,
      },
      {
        id: "wf-review",
        title: "Reviewing weak concepts",
        keywords: ["review", "weak", "spaced repetition", "flashcards"],
        body: `Let quizzes and flashcard ratings surface what you don't know yet, then loop: re-read the source, re-explain with Teach Me, and re-test. Spaced-repetition flashcards keep weak items coming back until they stick.

Use the [Knowledge Base](#feat-knowledge) to visualize how weak concepts relate to stronger ones.`,
      },
      {
        id: "wf-revise",
        title: "Revising completed topics",
        keywords: ["revise", "revision", "summary", "consolidate"],
        body: `For topics you've already learned, generate a concise **revision** sheet and skim it periodically. Use [Consistency](#feat-consistency) to keep your review habit on track.

Create [Whiteboards](#feat-whiteboards) of concept maps for a visual overview. Archive old material to the [Bin](#bin) once you're done.`,
      },
    ],
  },
  {
    id: "best-practices",
    title: "Best Practices",
    articles: [
      {
        id: "bp-quality",
        title: "Feed it good sources",
        keywords: ["quality", "sources", "tips"],
        body: `Answer quality is bounded by what you import. Prefer clean, text-based PDFs and well-structured notes. Scanned image-only PDFs may extract poorly — check that a document is searchable after indexing.

Add [Notebooks](#feat-notebooks) with your own syntheses alongside source documents.`,
      },
      {
        id: "bp-scope",
        title: "Scope to stay relevant",
        keywords: ["scope", "course", "focus"],
        body: `When you know which subject a question belongs to, scope it to that course or document. Tighter scope means more relevant retrieval and fewer off-topic citations.

Use courses from the start — migrating material later is manual.`,
      },
      {
        id: "bp-verify",
        title: "Trust, but verify citations",
        keywords: ["citations", "verify", "trust"],
        body: `Click through citations on important answers. Grounded generation is far more reliable than ungrounded chat, but the source passage is always the final word.

Use [RAG Trace](#feat-trace) to audit retrieval quality if answers seem off.`,
      },
    ],
  },
  {
    id: "shortcuts",
    title: "Keyboard Shortcuts",
    articles: [
      {
        id: "ks-global",
        title: "Global & navigation",
        keywords: ["keyboard", "shortcut", "command", "palette", "search"],
        body: `| Action | Shortcut |
| --- | --- |
| Command palette / search | \`⌘K\` |
| Sidebar toggle | \`⌘B\` |`,
      },
      {
        id: "ks-tours",
        title: "Tours & guidance",
        keywords: ["tour", "help", "replay", "guidance"],
        body: `Inside a tour you can use the popover buttons or your keyboard to move Next/Back and to close. Replay any page's tour from the **Help (?)** menu in the top bar, and manage guidance in **Settings → Help & Guidance**.

You can turn off interactive tours and contextual tips there, or reset all walkthroughs to see them again.`,
      },
    ],
  },
  {
    id: "settings-plugins",
    title: "Settings & Plugins",
    articles: [
      {
        id: "sp-settings",
        title: "Settings overview",
        keywords: ["settings", "configure", "preferences"],
        body: `The **Settings** page has several tabs:

- **General** — app-level preferences
- **Models** — configure which Ollama model handles each task
- **Shortcuts** — reference for all keyboard shortcuts
- **Help & Guidance** — manage tours, reset walkthroughs
- **Data** — export, import, or nuke all data
- **Plugins** — install, enable, or disable plugins

**Nuke Data** in *Data* tab clears everything — local data, guidance state, and tours will act like first visit again. This is irreversible.`,
      },
      {
        id: "sp-plugins",
        title: "Plugins & extensions",
        keywords: ["plugin", "extension", "excalidraw", "plantuml", "cloud"],
        body: `ScholarAI supports plugins that add optional features:

- **Whiteboards** — Excalidraw-based visual canvas (enabled by default)
- **PlantUML** — UML diagram rendering
- **Reading Annotations** — categorized sticky notes and region drawing in Reading mode (enabled by default)
- **Cloud Providers** — connect to Gemini, Groq, or OpenRouter as alternative model backends (experimental)

Manage plugins in **Settings → Plugins**. Install, enable, or disable them there.`,
      },
    ],
  },
  {
    id: "faq",
    title: "FAQ",
    articles: [
      {
        id: "faq-cloud",
        title: "Is my data sent to the cloud?",
        keywords: ["privacy", "local", "cloud", "offline"],
        body: `No. ScholarAI is local-first — documents, the vector index, and model inference all run on your machine.

You can optionally connect cloud model providers (Gemini, Groq, OpenRouter) if you prefer cloud inference, but your document data stays local.`,
      },
      {
        id: "faq-formats",
        title: "What file types can I import?",
        keywords: ["formats", "pdf", "markdown", "txt"],
        body: `PDF, Markdown (\`.md\`), and plain text (\`.txt\`). Text-based PDFs work best; image-only scans may not extract cleanly.`,
      },
      {
        id: "faq-tours-off",
        title: "Can I turn off the tours and tips?",
        keywords: ["disable", "tours", "tips", "preferences"],
        body: `Yes. Toggle interactive tours and contextual tips in **Settings → Help & Guidance** (or from the **Help (?)** menu). You can also reset all walkthroughs there to see them again.`,
      },
      {
        id: "faq-cloud-models",
        title: "Can I use cloud models instead of running Ollama?",
        keywords: ["cloud", "gemini", "groq", "openrouter", "provider", "api"],
        body: `Yes, if you don't want to run models locally. Enable the Cloud Providers plugin in **Settings → Plugins**, then go to **Settings → Models** to connect your API keys for Gemini, Groq, or OpenRouter.

Model routing and per-task budget controls are available in the same settings. Usage tracking shows token consumption per provider.`,
      },
      {
        id: "faq-scratchpad",
        title: "What is the scratchpad for?",
        keywords: ["scratchpad", "doodle", "quick", "draw", "canvas"],
        body: `The scratchpad is a quick-draw canvas available from any page via the bottom drawer. Use it for temporary sketches, equations, or diagrams without leaving your current view. It persists across sessions.`,
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    articles: [
      {
        id: "ts-empty",
        title: "Answers say there's no information",
        keywords: ["no results", "empty", "retrieval", "indexing"],
        body: `Usually the topic isn't in your indexed material, or the document didn't extract well. Confirm the document finished indexing on the **Documents** page, widen your scope, or add a better source.

Check [RAG Trace](#feat-trace) to see what was actually retrieved.`,
      },
      {
        id: "ts-models",
        title: "Generation seems stuck or fails",
        keywords: ["ollama", "model", "stuck", "error", "slow"],
        body: `Local generation depends on the model backend (Ollama) running and the required models being available. If a task hangs or errors, make sure the backend is up and the configured models are installed, then retry.

For cloud provider setups, check your API key is valid and the provider is reachable.`,
      },
      {
        id: "ts-reset",
        title: "I want to start fresh",
        keywords: ["reset", "nuke", "clear", "delete"],
        body: `**Settings → Data → Nuke Data** clears your local data and resets the app — including guidance state, so tours behave as first-visit again. This is irreversible, so export anything you want to keep first.`,
      },
      {
        id: "ts-bin",
        title: "Where do deleted items go?",
        keywords: ["bin", "trash", "delete", "restore", "recover"],
        body: `Deleted artifacts (documents, courses, flashcards, notebooks, whiteboards) go to the **Bin**. From there you can restore them or delete permanently. Items in the bin are auto-cleared after 10 days.`,
      },
    ],
  },
];
