/**
 * Content for the comprehensive in-app Guide (Layer 4). Pure data — the Guide
 * page renders article bodies with the shared MarkdownRenderer. Add a section or
 * article here and it shows up in the Guide nav + search automatically.
 *
 * Internal links: use a markdown link to `#<article-id>` to cross-reference
 * another article (e.g. `[exam prep](#wf-exam)`); article containers carry that id.
 */

export interface GuideArticle {
  id: string;
  title: string;
  keywords?: string[];
  /** Markdown. Rendered via MarkdownRenderer. */
  body: string;
}

export interface GuideSection {
  id: string;
  title: string;
  articles: GuideArticle[];
}

export const guideSections: GuideSection[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    articles: [
      {
        id: "gs-what",
        title: "What is ScholarAI?",
        keywords: ["overview", "intro", "about", "rag"],
        body: `ScholarAI is a **local-first study assistant**. It reads your own materials — PDFs, Markdown, notes — and turns them into an answerable, studyable knowledge base that lives entirely on your machine.

Everything runs locally: your documents are chunked, embedded, and indexed in a local vector store, and answers are generated by local models. Nothing is sent to the cloud.

**Where to start:** add a few documents on the [Documents](#gs-import) page, then try [Ask AI](#feat-ask) or generate study material.`,
      },
      {
        id: "gs-import",
        title: "Add your first documents",
        keywords: ["upload", "import", "pdf", "documents", "ingest"],
        body: `Open **Documents** and drag & drop your files, or click *Browse files*. Supported formats: PDF, Markdown, and plain text.

Each file is processed automatically — text extraction → chunking → embedding → indexing. Once indexing finishes, the document is searchable everywhere in the app.

> Tip: group related material into a **course** so you can scope answers and study sets to one subject.`,
      },
      {
        id: "gs-first-answer",
        title: "Get your first answer",
        keywords: ["ask", "question", "answer", "citations"],
        body: `Go to **Ask AI**, optionally narrow the scope to a course or single document, type a question, and send. Answers are grounded in your materials and cite the exact sources they came from — click a citation to see the passage.

If you'd rather *learn* a topic than just ask about it, try [Teach Me](#feat-teach).`,
      },
    ],
  },
  {
    id: "core-concepts",
    title: "Core Concepts",
    articles: [
      {
        id: "cc-rag",
        title: "Source-grounded answers (RAG)",
        keywords: ["rag", "retrieval", "grounding", "citations", "hallucination"],
        body: `ScholarAI uses **retrieval-augmented generation**: before answering, it retrieves the most relevant chunks from your indexed documents and asks the model to answer *only* from them. That's why answers carry citations — and why adding more (and better) source material directly improves answer quality.

If an answer can't be supported by your materials, the assistant should say so rather than guess.`,
      },
      {
        id: "cc-courses",
        title: "Courses & documents",
        keywords: ["course", "organize", "scope", "subject"],
        body: `A **course** is a workspace that groups related documents. Scoping a question, quiz, or revision sheet to a course keeps retrieval focused and results relevant.

You can leave everything in one place, but organizing by course pays off once you have material for several subjects.`,
      },
      {
        id: "cc-artifacts",
        title: "Study artifacts",
        keywords: ["flashcards", "quiz", "mindmap", "diagram", "generate", "artifact"],
        body: `Most generated study material — flashcards, quizzes, mind maps, diagrams, revision sheets — is created on demand from your documents and saved so you can return to it. Generate from the relevant page, review, and regenerate any time as your materials grow.`,
      },
    ],
  },
  {
    id: "features",
    title: "Features",
    articles: [
      {
        id: "feat-ask",
        title: "Ask AI",
        keywords: ["ask", "chat", "answer", "sources"],
        body: `Conversational, source-grounded Q&A over your materials. Narrow the scope to a course or document, ask, and inspect the cited passages in the sources panel. Toggle Socratic mode to be guided toward answers instead of handed them.`,
      },
      {
        id: "feat-teach",
        title: "Teach Me",
        keywords: ["teach", "learn", "lesson", "explain"],
        body: `Pick a concept and ScholarAI builds an interactive learning package — explanations plus supporting artifacts — to teach it step by step. Best when you want to *understand* a topic from scratch.`,
      },
      {
        id: "feat-reading",
        title: "Reading",
        keywords: ["reading", "deep", "lens", "explain", "highlight"],
        body: `Read a document in a focused reader with AI on the side: adjust the academic lens to simplify or deepen explanations, and pull context for anything confusing without leaving the page.`,
      },
      {
        id: "feat-study",
        title: "Flashcards, Quizzes & more",
        keywords: ["flashcards", "quiz", "mindmap", "diagram", "differences", "revision"],
        body: `Generate spaced-repetition **flashcards**, self-test **quizzes**, **mind maps**, visual **diagrams**, comparison **difference tables**, and exam-ready **revision** sheets — each grounded in your own material. Find them in the sidebar under *Study Tools* and *Workspace*.`,
      },
      {
        id: "feat-exam",
        title: "Exam & PYQ Analysis",
        keywords: ["exam", "mock", "simulate", "pyq", "previous year"],
        body: `Simulate a real exam generated from your materials, then review your performance. **PYQ Analysis** mines previous-year questions to surface patterns and high-yield topics.`,
      },
    ],
  },
  {
    id: "workflows",
    title: "Workflows",
    articles: [
      {
        id: "wf-import",
        title: "Importing & organizing material",
        keywords: ["import", "organize", "course", "setup"],
        body: `1. Create or pick a **course** for the subject.
2. Add documents on the **Documents** page (drag & drop).
3. Wait for indexing to finish.
4. Confirm it worked by asking a quick question in [Ask AI](#feat-ask).

Good inputs make every other tool better — start here.`,
      },
      {
        id: "wf-learn",
        title: "Learning a new topic",
        keywords: ["learn", "study", "new topic", "teach"],
        body: `1. Use [Teach Me](#feat-teach) to get a structured explanation of the concept.
2. Read the source in [Reading](#feat-reading), lowering the lens if it's dense.
3. Ask follow-ups in [Ask AI](#feat-ask) for anything unclear.
4. Lock it in with a few [flashcards](#feat-study).`,
      },
      {
        id: "wf-exam",
        title: "Preparing for an exam",
        keywords: ["exam", "prep", "revision", "mock", "practice"],
        body: `1. Generate a **revision** sheet for each topic.
2. Run a **quiz** to find weak spots.
3. Take a full **Exam** simulation under time pressure.
4. Review misses and revisit those topics. Repeat until scores stabilize.`,
      },
      {
        id: "wf-review",
        title: "Reviewing weak concepts",
        keywords: ["review", "weak", "spaced repetition", "flashcards"],
        body: `Let quizzes and flashcard ratings surface what you don't know yet, then loop: re-read the source, re-explain with Teach Me, and re-test. Spaced-repetition flashcards keep weak items coming back until they stick.`,
      },
      {
        id: "wf-revise",
        title: "Revising completed topics",
        keywords: ["revise", "revision", "summary", "consolidate"],
        body: `For topics you've already learned, generate a concise **revision** sheet and skim it periodically. Use **Consistency** to keep your review habit on track.`,
      },
    ],
  },
  {
    id: "best-practices",
    title: "Best Practices",
    articles: [
      {
        id: "bp-quality",
        title: "Feed it good sources",
        keywords: ["quality", "sources", "tips"],
        body: `Answer quality is bounded by what you import. Prefer clean, text-based PDFs and well-structured notes. Scanned image-only PDFs may extract poorly — check that a document is searchable after indexing.`,
      },
      {
        id: "bp-scope",
        title: "Scope to stay relevant",
        keywords: ["scope", "course", "focus"],
        body: `When you know which subject a question belongs to, scope it to that course or document. Tighter scope means more relevant retrieval and fewer off-topic citations.`,
      },
      {
        id: "bp-verify",
        title: "Trust, but verify citations",
        keywords: ["citations", "verify", "trust"],
        body: `Click through citations on important answers. Grounded generation is far more reliable than ungrounded chat, but the source passage is always the final word.`,
      },
    ],
  },
  {
    id: "shortcuts",
    title: "Keyboard Shortcuts",
    articles: [
      {
        id: "ks-global",
        title: "Global",
        keywords: ["keyboard", "shortcut", "command", "palette", "search"],
        body: `| Action | Shortcut |
| --- | --- |
| Open command palette / search | \`⌘K\` |
| Navigate (when no input is focused) | press a page's letter, e.g. \`D\` Dashboard, \`A\` Ask AI, \`O\` Documents, \`F\` Flashcards |

The full per-page shortcut list lives in **Settings → Shortcuts**.`,
      },
      {
        id: "ks-tours",
        title: "Tours & guidance",
        keywords: ["tour", "help", "replay", "guidance"],
        body: `Inside a tour you can use the popover buttons or your keyboard to move Next/Back and to close. Replay any page's tour from the **Help (?)** menu in the top bar, and manage guidance in **Settings → Help & Guidance**.`,
      },
    ],
  },
  {
    id: "faq",
    title: "FAQ",
    articles: [
      {
        id: "faq-cloud",
        title: "Is my data sent to the cloud?",
        keywords: ["privacy", "local", "cloud", "offline"],
        body: `No. ScholarAI is local-first — documents, the vector index, and model inference all run on your machine.`,
      },
      {
        id: "faq-formats",
        title: "What file types can I import?",
        keywords: ["formats", "pdf", "markdown", "txt"],
        body: `PDF, Markdown (\`.md\`), and plain text (\`.txt\`). Text-based PDFs work best; image-only scans may not extract cleanly.`,
      },
      {
        id: "faq-tours-off",
        title: "Can I turn off the tours and tips?",
        keywords: ["disable", "tours", "tips", "preferences"],
        body: `Yes. Toggle interactive tours and contextual tips in **Settings → Help & Guidance** (or from the **Help (?)** menu). You can also reset all walkthroughs there to see them again.`,
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    articles: [
      {
        id: "ts-empty",
        title: "Answers say there's no information",
        keywords: ["no results", "empty", "retrieval", "indexing"],
        body: `Usually the topic isn't in your indexed material, or the document didn't extract well. Confirm the document finished indexing on the **Documents** page, widen your scope, or add a better source.`,
      },
      {
        id: "ts-models",
        title: "Generation seems stuck or fails",
        keywords: ["ollama", "model", "stuck", "error", "slow"],
        body: `Local generation depends on the model backend (Ollama) running and the required models being available. If a task hangs or errors, make sure the backend is up and the configured models are installed, then retry.`,
      },
      {
        id: "ts-reset",
        title: "I want to start fresh",
        keywords: ["reset", "nuke", "clear", "delete"],
        body: `**Settings → Data → Nuke Data** clears your local data and resets the app — including guidance state, so tours behave as first-visit again. This is irreversible, so export anything you want to keep first.`,
      },
    ],
  },
];
